```{r}
nftools::nf_library(c(
  'lubridate',
  'tidyverse'
))
# Threshold is 5
load('SepsisR01_UCSFDeIDCDW_2023-12-04.RData')

# Sort by timestamp
flowsheet <- flowsheet %>%
  mutate(timestamp = ymd_hm(paste(DateKeyValue, TimeOfDayKeyValue)))

# Sort by collection time, not result time
labs <- labs %>%
  mutate(timestamp = ymd_hm(paste(CollectionDateKeyValue, CollectionTimeOfDayKeyValue)))
```
```{r Temperature}
temp <- flowsheet %>%
  filter(FlowsheetRowDisplayName == 'Temp' & !is.na(NumericValue) & Accepted == 1) %>%
  mutate(temp = ifelse(NumericValue > 42, (NumericValue - 32) * 5/9, NumericValue)) %>%
  filter(temp >= 32 & temp <= 42) %>%
  group_by(EncounterKey) %>%
  arrange(timestamp) %>%
  slice(1) %>%
  mutate(SIRS_TEMP = ifelse(temp > 38 | temp < 36, 1, 0))

temp %>% ungroup %>% count(SIRS_TEMP)
```

```{r Pulse}
pulse <- flowsheet %>%
  filter(FlowsheetRowDisplayName == 'Pulse' & !is.na(NumericValue) & Accepted == 1) %>%
  group_by(EncounterKey) %>%
  arrange(timestamp) %>%
  slice(1) %>%
  mutate(SIRS_PULSE = ifelse(NumericValue > 90, 1, 0))

pulse %>% ungroup %>% count(SIRS_PULSE)
```

```{r Respiratory Rate}
resp <- flowsheet %>%
  filter(FlowsheetRowDisplayName == 'Resp' & !is.na(NumericValue) & Accepted == 1) %>%
  group_by(EncounterKey) %>%
  arrange(timestamp) %>%
  slice(1) %>%
  mutate(SIRS_RESP_RATE = ifelse(NumericValue > 20, 1, 0))

resp %>% ungroup %>% count(SIRS_RESP_RATE)
```

```{r WBC }
wbc <- labs %>%
  mutate(
    parsed_value = parse_number(Value),
    is_na_coercion = is.na(parsed_value)
  )
print(wbc %>% ungroup %>% filter(is_na_coercion) %>% count(Value))

wbc <- wbc %>%
  mutate(NumericValue = as.numeric(Value)) %>%
  filter(ComponentName== 'WBC Count' & !is.na(NumericValue)) %>%
  group_by(EncounterKey) %>%
  arrange(timestamp) %>%
  slice(1) %>%
  mutate(SIRS_WBC = ifelse(NumericValue > 12 | NumericValue < 4, 1, 0))


# Also need to account for bands

wbc %>% ungroup %>% count(SIRS_WBC)
```
```{r}
labs <- labs %>%
    mutate(
    parsed_value = parse_number(Value),
    is_na_coercion = is.na(parsed_value)
  )

# Print the resulting data frame
labs %>% filter(is_na_coercion) %>% count(Value)
```


```{r}
sirs <- resp %>% select(EncounterKey, contains('NEWS')) %>%
  merge(spo2 %>% select(EncounterKey, contains('NEWS')), on='EncounterKey', all=T) %>%
  merge(suppox %>% select(EncounterKey, contains('NEWS')), on='EncounterKey', all=T) %>%
  merge(temp %>% select(EncounterKey, contains('NEWS')), on='EncounterKey', all=T) %>%
  merge(bp %>% select(EncounterKey, contains('NEWS')), on='EncounterKey', all=T) %>%
  merge(pulse %>% select(EncounterKey, contains('NEWS')), on='EncounterKey', all=T) %>%
  merge(consciousness %>% select(EncounterKey, NEWS_CONSCIOUSNESS), on='EncounterKey', all=T) %>%
  mutate(NEWS_2_SCORE = rowSums(select(., -EncounterKey), na.rm = TRUE))

write.csv(news, file='news2_scores.csv')
```

