```{r}
nftools::nf_library(c(
  'lubridate',
  'tidyverse',
  'data.table'
))

base <- '~/src/Sepsis-R01/Data_All_2023-12-21/'

dx <- fread(paste0(base, 'dx_all.csv'))
ed_keys <- fread(paste0(base, 'ed_keys.csv'))
enc_dx <- fread(paste0(base, 'enc_dx.csv'))
flowsheet <- fread(paste0(base, 'flowsheet.csv'))
hosp_adm <- fread(paste0(base, 'hosp_adm.csv'))
labs <- fread(paste0(base, 'labs.csv'))
pt <- fread(paste0(base, 'pt.csv')) %>%
  mutate(
    has_birthdate = ifelse(is.na(BirthDate), F, T)
  )
durationdim <- fread(paste0('~/src/Sepsis-R01/', 'durationdim.csv')) %>% 
  select(DurationKey, Years) %>%
  rename(DurationAge=Years)
ed <- fread(paste0(base, 'ed.csv')) %>%
  merge(durationdim, by.x = 'AgeKey', by.y='DurationKey', all.x=T)

# Sort by timestamp
flowsheet <- flowsheet %>%
  mutate(timestamp = ymd_hm(paste(DateKeyValue, TimeOfDayKeyValue))) %>%
  dplyr::filter(EncounterKey %in% ed_keys$EncounterKey)

# Sort by collection time, not result time
labs <- labs %>%
  mutate(timestamp = ymd_hm(paste(CollectionDateKeyValue, CollectionTimeOfDayKeyValue)))

ed <- ed %>%
  mutate(ed_timestamp = ymd_hm(paste(ArrivalDateKeyValue, ArrivalTimeOfDayKeyValue)))
```

```{r WBC}
wbc <- labs %>%
  mutate(
    parsed_value = parse_number(Value),
    is_na_coercion = is.na(parsed_value)
  )
print(wbc %>% ungroup %>% filter(is_na_coercion) %>% count(Value))

wbc <- wbc %>%
  mutate(NumericValue = as.numeric(Value)) %>%
  filter(ComponentName== 'WBC Count' & !is.na(NumericValue)) %>%
  group_by(EncounterKey) %>%
  arrange(timestamp) %>%
  slice(1) %>%
  merge(ed %>% select(EncounterKey, ed_timestamp), by='EncounterKey', all.x=T) %>%
  mutate(
    TWO_HOURS = ifelse(difftime(timestamp, ed_timestamp, units = "hours") < 2, 1, 0),
    SIRS_WBC = ifelse(TWO_HOURS & (NumericValue > 12 | NumericValue < 4), 1, 0)
  ) %>%
  rename(wbc = NumericValue)

wbc %>% ungroup %>% count(SIRS_WBC)
```

```{r Temperature}
temp <- flowsheet %>%
  filter(FlowsheetRowDisplayName == 'Temp' & !is.na(NumericValue) & Accepted == 1) %>%
  mutate(temp = ifelse(NumericValue > 42, (NumericValue - 32) * 5/9, NumericValue)) %>%
  filter(temp >= 32 & temp <= 42) %>%
  group_by(EncounterKey) %>%
  arrange(timestamp) %>%
  slice(1) %>%
  merge(ed %>% select(EncounterKey, ed_timestamp), by='EncounterKey', all.x=T) %>%
  mutate(
    TEMP_TWO_HOURS = ifelse(difftime(timestamp, ed_timestamp, units = "hours") < 2, 1, 0),
    SIRS_TEMP = ifelse(TEMP_TWO_HOURS & (temp > 38 | temp < 36), 1, 0)
  )

temp %>% ungroup %>% count(SIRS_TEMP)
```


```{r}
df <- ed_keys %>%
  merge(wbc %>% select(PatientKey, EncounterKey, wbc, TWO_HOURS, SIRS_WBC), by='EncounterKey', all.x=T) %>%
  merge(temp %>% select(PatientKey, EncounterKey, temp, SIRS_TEMP), by='EncounterKey', all.x=T) %>%
  mutate(
    analyzed = ifelse(!is.na(wbc), T, ifelse(!is.na(temp), T, F)),
    summation = rowSums(select(., contains('SIRS')), na.rm = TRUE),
    include = ifelse(summation > 0, T, F)
    )

write.csv(df, file='inclusion.csv')
```

```{r eval=FALSE, include=FALSE}
base <- '~/src/Sepsis-R01/Data_Inc_2023-12-08/'

dx <- fread(paste0(base, 'dx_enc_icd.csv'))
death <- fread(paste0(base, 'death.csv'))
durationdim <- fread(paste0('~/src/Sepsis-R01/', 'durationdim.csv')) %>% 
  select(DurationKey, Years) %>%
  rename(DurationAge=Years)
#ed <- fread(paste0(base, 'ed.csv')) %>%
ed <- ed %>%
  merge(durationdim, by.x = 'AgeKey', by.y='DurationKey', all.x=T)
assess <- fread(paste0(base, 'flowsheet_assess.csv'))
resp <- fread(paste0(base, 'flowsheet_resp.csv'))
hosp <- fread(paste0(base, 'hosp_adm.csv'))
icu_reg <- fread(paste0(base, 'icu_reg.csv'))
enc_keys <- fread(paste0(base, 'enc_keys.csv'))
insurance <- fread(paste0(base, 'insurance.csv'))
labs <- fread(paste0(base, 'labs.csv'))
med_ab <- fread(paste0(base, 'med_ab.csv'))
colnames(med_ab)[which(colnames(med_ab) == "EncounterKey")[2]] <- "NewEncounterKey"

pt <- pt %>% #fread(paste0(base, 'pt.csv')) %>%
  mutate(
    has_birthdate = ifelse(is.na(BirthDate), F, T)
  )
pt_keys <- fread(paste0(base, 'pt_keys.csv'))

map_icd_to_category <- function(icd_code) {
  # Extract the first character of the ICD-10 code
  first_char <- substr(icd_code, 1, 1)

  # Map ICD-10 codes to broader categories based on the first character
  category <- switch(first_char,
    A = "Infectious and Parasitic Diseases",
    B = "Infectious and Parasitic Diseases",
    C = "Neoplasms (Tumors)",
    D = ifelse(grepl("^D[5-8]", icd_code), "Blood and Immune System Disorders", "Other"),
    E = "Endocrine, Nutritional, and Metabolic Diseases",
    F = "Mental and Behavioral Disorders",
    G = "Diseases of the Nervous System",
    H = "Diseases of the Eye and Adnexa",
    I = "Diseases of the Circulatory System",
    J = "Diseases of the Respiratory System",
    K = "Diseases of the Digestive System",
    L = "Diseases of the Skin and Subcutaneous Tissue",
    M = "Diseases of the Musculoskeletal System and Connective Tissue",
    N = "Diseases of the Genitourinary System",
    O = "Pregnancy, Childbirth, and the Puerperium",
    P = "Conditions Originating in the Perinatal Period",
    Q = "Congenital Malformations, Deformations, and Chromosomal Abnormalities",
    R = "Symptoms, Signs, and Abnormal Findings",
    S = "Injury, Poisoning, and Other Consequences of External Causes",
    T = "Injury, Poisoning, and Other Consequences of External Causes",
    U = "Codes for Special Purposes",
    Other = "Other"
  )

  return(category)
}

#dx <- dx %>%
#  mutate(ICD_Category = map_icd_to_category(icd_value))

```
```{r Define Sepsis ICD Codes}
icd_codes <- c(dx %>% 
                 filter(grepl('sepsis|septic', icd_l3_name, ignore.case=T)) %>% 
                 pull(icd_value) %>% 
                 unique,
               dx %>% 
                 filter(grepl('sepsis|septic', icd_l4_name, ignore.case=T)) %>% 
                 pull(icd_value) %>% 
                 unique,
               dx %>% 
                 filter(grepl('sepsis|septic', icd_l5_name, ignore.case=T)) %>%
                 pull(icd_value) %>% 
                 unique,
               dx %>% 
                 filter(grepl('sepsis|septic', icd_l6_name, ignore.case=T)) %>%
                 pull(icd_value) %>% 
                 unique
) %>% unique %>% sort

shock_icd_codes <- c(
  dx %>% 
    filter(grepl('sepsis|septic', icd_l3_name, ignore.case=T) & 
             grepl('shock', icd_l3_name, ignore.case=T) & 
             !grepl('without', icd_l3_name, ignore.case=T)) %>% 
    pull(icd_value) %>% 
    unique,
  dx %>% 
    filter(grepl('sepsis|septic', icd_l4_name, ignore.case=T) & 
             grepl('shock', icd_l4_name, ignore.case=T) & 
             !grepl('without', icd_l4_name, ignore.case=T)) %>% 
    pull(icd_value) %>% 
    unique,
  dx %>% 
    filter(grepl('sepsis|septic', icd_l5_name, ignore.case=T) & 
             grepl('shock', icd_l5_name, ignore.case=T) & 
             !grepl('without', icd_l5_name, ignore.case=T)) %>% 
    pull(icd_value) %>% 
    unique,
  dx %>% 
    filter(grepl('sepsis|septic', icd_l6_name, ignore.case=T) & 
             grepl('shock', icd_l6_name, ignore.case=T) & 
             !grepl('without', icd_l6_name, ignore.case=T)) %>% 
    pull(icd_value) %>% 
    unique,
  dx %>% 
    filter(grepl('sepsis|septic', icd_l7_name, ignore.case=T) & 
             grepl('shock', icd_l7_name, ignore.case=T) & 
             !grepl('without', icd_l7_name, ignore.case=T)) %>% 
    pull(icd_value) %>% 
    unique
) %>% unique %>% sort
```


```{r}
dx_trim <- dx %>%
  select(
    'PatientKey',
    'EncounterKey',
    'icd_value'
  ) %>%
  mutate(
    sepsis = ifelse(icd_value %in% icd_codes, 1, 0),
    septic_shock = ifelse(icd_value %in% shock_icd_codes, 1, 0)
  ) %>%
  filter(EncounterKey %in% ed_keys$EncounterKey) %>%
  group_by(EncounterKey) %>%
  summarize(
#    PatientKey = first(PatientKey),
    sepsis = max(sepsis),
    septic_shock = max(septic_shock)
  ) %>%
  mutate(
    sepsis = ifelse(sepsis == 1, T, F),
    septic_shock = ifelse(septic_shock == 1, T, F),
  ) %>%
  ungroup

pt_trim <- pt %>%
  select(
    'BirthDate',
    'has_birthdate',
    'PatientKey',
    'Status',
    'MaritalStatus',
    'Religion',
    'SmokingStatus',
    'PrimaryFinancialClass',
    'HighestLevelOfEducation',
    'SexAssignedAtBirth',
    'GenderIdentity',
    'SexualOrientation',
    'UCSFDerivedRaceEthnicity_X'
  ) %>%
  distinct(.keep_all = TRUE) %>%
  ungroup

tabledf <- df %>%
  merge(dx_trim, by='EncounterKey', all.x = T) %>%
  merge(ed %>% dplyr::select(EncounterKey, DurationAge), by='EncounterKey', all.x = T) %>% 
  merge(pt_trim, by='PatientKey', all.x = T) %>%
  mutate(
    processed_birthdate = lubridate::ymd(BirthDate),
    age_days = as.numeric(difftime(lubridate::ymd(ArrivalDateKeyValue), processed_birthdate, units='days')),
    age = age_days/365.25,
    age_delta = age - DurationAge,
    SIRS_WBC = as.factor(SIRS_WBC),
    SIRS_TEMP = as.factor(SIRS_TEMP),
  ) %>%
  mutate_if(is.character, 
    list(~ ifelse(grepl("^\\*|^$|^Missing$", .), NA, .))
  )

columns <- c(
#    'Status',
#    'age',
    'analyzed',
    'SIRS_WBC',
    'SIRS_TEMP',
    'DurationAge',
#    'age_delta',
#    'has_birthdate',
    'SexAssignedAtBirth',
    'GenderIdentity',
    'MaritalStatus',
    'Religion',
    'SmokingStatus',
    'PrimaryFinancialClass',
    'SexualOrientation',
    'wbc',
    'temp',
    'sepsis',
    'septic_shock'
)

nftools::nf_table1(columns, 'include', tabledf, calculate_pvalue = F)

tabledf$year <- tabledf$ArrivalDateKeyValue%>% year
nftools::nf_table1(columns, 'year', tabledf, calculate_pvalue = F)
```
```{r Summary stats for R01 Writeup}
# Number of visits per year
tabledf %>% count(year) %>% pull(n) %>% summary
```

```{r eSOFA}


```

